name: module_router
description: "A new Flutter package project."
version: 1.0.0
homepage: https://github.com/TercyoStorck/module_router

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
